<h1>TESTING PYTHON</h1>

In [1]:
print("hello word")

hello word


<h1>DOWNLOADING NECESSARY LIBRARIES</h1>

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC37\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC37\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC37\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC37\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


<h1>IMPORT LIBRARIES</h1>

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn  as sns
import pandas as pd

<h1>IMPPORT DATASET TO DATA FRAME</h1>

In [7]:
birds = pd.read_csv('datasets\\penguins.csv')

In [8]:
birds

rowid    species     island  bill_length_mm  bill_depth_mm  \
0        1     Adelie  Torgersen            39.1           18.7   
1        2     Adelie  Torgersen            39.5           17.4   
2        3     Adelie  Torgersen            40.3           18.0   
3        4     Adelie  Torgersen             NaN            NaN   
4        5     Adelie  Torgersen            36.7           19.3   
..     ...        ...        ...             ...            ...   
339    340  Chinstrap      Dream            55.8           19.8   
340    341  Chinstrap      Dream            43.5           18.1   
341    342  Chinstrap      Dream            49.6           18.2   
342    343  Chinstrap      Dream            50.8           19.0   
343    344  Chinstrap      Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  
0                181.0       3750.0    male  2007  
1                186.0       3800.0  female  2007  
2                195.0       3250.0  female  2007  
3                  NaN          NaN     NaN  2007  
4                193.0       3450.0  female  2007  
..                 ...          ...     ...   ...  
339              207.0       4000.0    male  2009  
340              202.0       3400.0  female  2009  
341              193.0       3775.0    male  2009  
342              210.0       4100.0    male  2009  
343              198.0       3775.0  female  2009  

[344 rows x 9 columns]

In [9]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   rowid              344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object 
 8   year               344 non-null    int64  
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB


In [10]:
birds.isnull()

rowid  species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    False    False   False           False          False              False   
1    False    False   False           False          False              False   
2    False    False   False           False          False              False   
3    False    False   False            True           True               True   
4    False    False   False           False          False              False   
..     ...      ...     ...             ...            ...                ...   
339  False    False   False           False          False              False   
340  False    False   False           False          False              False   
341  False    False   False           False          False              False   
342  False    False   False           False          False              False   
343  False    False   False           False          False              False   

     body_mass_g    sex   year  
0          False  False  False  
1          False  False  False  
2          False  False  False  
3           True   True  False  
4          False  False  False  
..           ...    ...    ...  
339        False  False  False  
340        False  False  False  
341        False  False  False  
342        False  False  False  
343        False  False  False  

[344 rows x 9 columns]

In [11]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

<h1>Descriptive Analytics</h1>

In [12]:
birds.describe().T

count         mean         std     min       25%      50%  \
rowid              344.0   172.500000   99.448479     1.0    86.750   172.50   
bill_length_mm     342.0    43.921930    5.459584    32.1    39.225    44.45   
bill_depth_mm      342.0    17.151170    1.974793    13.1    15.600    17.30   
flipper_length_mm  342.0   200.915205   14.061714   172.0   190.000   197.00   
body_mass_g        342.0  4201.754386  801.954536  2700.0  3550.000  4050.00   
year               344.0  2008.029070    0.818356  2007.0  2007.000  2008.00   

                       75%     max  
rowid               258.25   344.0  
bill_length_mm       48.50    59.6  
bill_depth_mm        18.70    21.5  
flipper_length_mm   213.00   231.0  
body_mass_g        4750.00  6300.0  
year               2009.00  2009.0

<h1>filtering</h1>

In [13]:
birds['body_mass_g']

0      3750.0
1      3800.0
2      3250.0
3         NaN
4      3450.0
        ...  
339    4000.0
340    3400.0
341    3775.0
342    4100.0
343    3775.0
Name: body_mass_g, Length: 344, dtype: float64

In [14]:
birds['sex']

0        male
1      female
2      female
3         NaN
4      female
        ...  
339      male
340    female
341      male
342      male
343    female
Name: sex, Length: 344, dtype: object

<h1>HOW TO DEFINE/CREATE YOUR OWN COLUMN</h1>

In [15]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000,1)

In [16]:
birds

rowid    species     island  bill_length_mm  bill_depth_mm  \
0        1     Adelie  Torgersen            39.1           18.7   
1        2     Adelie  Torgersen            39.5           17.4   
2        3     Adelie  Torgersen            40.3           18.0   
3        4     Adelie  Torgersen             NaN            NaN   
4        5     Adelie  Torgersen            36.7           19.3   
..     ...        ...        ...             ...            ...   
339    340  Chinstrap      Dream            55.8           19.8   
340    341  Chinstrap      Dream            43.5           18.1   
341    342  Chinstrap      Dream            49.6           18.2   
342    343  Chinstrap      Dream            50.8           19.0   
343    344  Chinstrap      Dream            50.2           18.7   

     flipper_length_mm  body_mass_g     sex  year  weight  
0                181.0       3750.0    male  2007     3.8  
1                186.0       3800.0  female  2007     3.8  
2                195.0       3250.0  female  2007     3.2  
3                  NaN          NaN     NaN  2007     NaN  
4                193.0       3450.0  female  2007     3.4  
..                 ...          ...     ...   ...     ...  
339              207.0       4000.0    male  2009     4.0  
340              202.0       3400.0  female  2009     3.4  
341              193.0       3775.0    male  2009     3.8  
342              210.0       4100.0    male  2009     4.1  
343              198.0       3775.0  female  2009     3.8  

[344 rows x 10 columns]

In [17]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
weight                2
dtype: int64

<h1>WHAT TO DO WITH NULL VALUES</h1>

In [18]:
birds['body_mass_g'].mean()

np.float64(4201.754385964912)

In [19]:
birds['sex'].mode()

0    male
Name: sex, dtype: object

In [20]:
birds['bill_length_mm'] = birds['bill_length_mm'].fillna(birds['bill_length_mm'].mean())

In [21]:
birds['body-mass_g'] = birds['body_mass_g'].fillna(birds['body_mass_g'].mean())

In [22]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        0
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
weight                2
body-mass_g           0
dtype: int64

In [23]:
birds['sex'] = birds['sex'].fillna(birds['sex'].mode()[0])

In [24]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
sex                  0
year                 0
weight               2
body-mass_g          0
dtype: int64

In [25]:
birds['flipper_length_mm'] = birds['flipper_length_mm'].fillna(birds['flipper_length_mm'].mean())

In [26]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        2
flipper_length_mm    0
body_mass_g          2
sex                  0
year                 0
weight               2
body-mass_g          0
dtype: int64

In [27]:
birds['bill_depth_mm'] = birds['bill_depth_mm'].fillna(birds['bill_depth_mm'].mean())

In [28]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          2
sex                  0
year                 0
weight               2
body-mass_g          0
dtype: int64

In [29]:
birds['weight'] = birds['weight'].fillna(birds['weight'].mean())

In [30]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          2
sex                  0
year                 0
weight               0
body-mass_g          0
dtype: int64

In [31]:
birds['body_mass_g'] = birds['body_mass_g'].fillna(birds['body_mass_g'].mean())

In [32]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
body-mass_g          0
dtype: int64

In [33]:
birds.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   rowid              344 non-null    int64  
 1   species            344 non-null    object 
 2   island             344 non-null    object 
 3   bill_length_mm     344 non-null    float64
 4   bill_depth_mm      344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    object 
 8   year               344 non-null    int64  
 9   weight             344 non-null    float64
 10  body-mass_g        344 non-null    float64
dtypes: float64(6), int64(2), object(3)
memory usage: 29.7+ KB


In [34]:
birds['year'] = birds['year'].astype('category')

In [35]:
birds['species'] = birds ['species'].astype('category')

In [36]:
birds['rowid'] = birds ['rowid'].astype('category')

In [37]:
birds['island'] = birds ['island'].astype('category')

In [38]:
birds['sex'] = birds ['sex'].astype('category')

In [39]:
birds.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   rowid              344 non-null    category
 1   species            344 non-null    category
 2   island             344 non-null    category
 3   bill_length_mm     344 non-null    float64 
 4   bill_depth_mm      344 non-null    float64 
 5   flipper_length_mm  344 non-null    float64 
 6   body_mass_g        344 non-null    float64 
 7   sex                344 non-null    category
 8   year               344 non-null    category
 9   weight             344 non-null    float64 
 10  body-mass_g        344 non-null    float64 
dtypes: category(5), float64(6)
memory usage: 29.6 KB


<h1>conditional operators</h1>

In [40]:
birds[birds['species'] == 'Adelie' ].count()

rowid                152
species              152
island               152
bill_length_mm       152
bill_depth_mm        152
flipper_length_mm    152
body_mass_g          152
sex                  152
year                 152
weight               152
body-mass_g          152
dtype: int64

In [41]:
birds[birds['species'] == 'Gentoo' ].count()

rowid                124
species              124
island               124
bill_length_mm       124
bill_depth_mm        124
flipper_length_mm    124
body_mass_g          124
sex                  124
year                 124
weight               124
body-mass_g          124
dtype: int64

In [42]:
birds[birds['species'] == 'Chinstrap' ].count()

rowid                68
species              68
island               68
bill_length_mm       68
bill_depth_mm        68
flipper_length_mm    68
body_mass_g          68
sex                  68
year                 68
weight               68
body-mass_g          68
dtype: int64

In [43]:
A =birds[birds['species'] == 'Chinstrap' ].count()
B =birds[birds['species'] == 'Adelie' ].count()
C =birds[birds['species'] == 'Gentoo' ].count()

<h1>HOW MANY GENTOO SPECIES HAVE WEIHT MORE THAN 3KG

In [44]:
birds['weight'] > 3

0      True
1      True
2      True
3      True
4      True
       ... 
339    True
340    True
341    True
342    True
343    True
Name: weight, Length: 344, dtype: bool

In [45]:
birds['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [46]:
birds['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [47]:
birds['species'] == 'Gentoo'

0      False
1      False
2      False
3      False
4      False
       ...  
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

<h1>insight no 1</h1>

In [48]:
birds['wkilo'] = np.round(birds['body_mass_g']/ 100,2)
birds['wkilo']


0      37.50
1      38.00
2      32.50
3      42.02
4      34.50
       ...  
339    40.00
340    34.00
341    37.75
342    41.00
343    37.75
Name: wkilo, Length: 344, dtype: float64

In [49]:
adelie_biscoe = birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Biscoe')] 
adelie_biscoe

rowid species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
20     21  Adelie  Biscoe            37.8           18.3              174.0   
21     22  Adelie  Biscoe            37.7           18.7              180.0   
22     23  Adelie  Biscoe            35.9           19.2              189.0   
23     24  Adelie  Biscoe            38.2           18.1              185.0   
24     25  Adelie  Biscoe            38.8           17.2              180.0   
25     26  Adelie  Biscoe            35.3           18.9              187.0   
26     27  Adelie  Biscoe            40.6           18.6              183.0   
27     28  Adelie  Biscoe            40.5           17.9              187.0   
28     29  Adelie  Biscoe            37.9           18.6              172.0   
29     30  Adelie  Biscoe            40.5           18.9              180.0   
50     51  Adelie  Biscoe            39.6           17.7              186.0   
51     52  Adelie  Biscoe            40.1           18.9              188.0   
52     53  Adelie  Biscoe            35.0           17.9              190.0   
53     54  Adelie  Biscoe            42.0           19.5              200.0   
54     55  Adelie  Biscoe            34.5           18.1              187.0   
55     56  Adelie  Biscoe            41.4           18.6              191.0   
56     57  Adelie  Biscoe            39.0           17.5              186.0   
57     58  Adelie  Biscoe            40.6           18.8              193.0   
58     59  Adelie  Biscoe            36.5           16.6              181.0   
59     60  Adelie  Biscoe            37.6           19.1              194.0   
60     61  Adelie  Biscoe            35.7           16.9              185.0   
61     62  Adelie  Biscoe            41.3           21.1              195.0   
62     63  Adelie  Biscoe            37.6           17.0              185.0   
63     64  Adelie  Biscoe            41.1           18.2              192.0   
64     65  Adelie  Biscoe            36.4           17.1              184.0   
65     66  Adelie  Biscoe            41.6           18.0              192.0   
66     67  Adelie  Biscoe            35.5           16.2              195.0   
67     68  Adelie  Biscoe            41.1           19.1              188.0   
100   101  Adelie  Biscoe            35.0           17.9              192.0   
101   102  Adelie  Biscoe            41.0           20.0              203.0   
102   103  Adelie  Biscoe            37.7           16.0              183.0   
103   104  Adelie  Biscoe            37.8           20.0              190.0   
104   105  Adelie  Biscoe            37.9           18.6              193.0   
105   106  Adelie  Biscoe            39.7           18.9              184.0   
106   107  Adelie  Biscoe            38.6           17.2              199.0   
107   108  Adelie  Biscoe            38.2           20.0              190.0   
108   109  Adelie  Biscoe            38.1           17.0              181.0   
109   110  Adelie  Biscoe            43.2           19.0              197.0   
110   111  Adelie  Biscoe            38.1           16.5              198.0   
111   112  Adelie  Biscoe            45.6           20.3              191.0   
112   113  Adelie  Biscoe            39.7           17.7              193.0   
113   114  Adelie  Biscoe            42.2           19.5              197.0   
114   115  Adelie  Biscoe            39.6           20.7              191.0   
115   116  Adelie  Biscoe            42.7           18.3              196.0   

     body_mass_g     sex  year  weight  body-mass_g  wkilo  
20        3400.0  female  2007     3.4       3400.0  34.00  
21        3600.0    male  2007     3.6       3600.0  36.00  
22        3800.0  female  2007     3.8       3800.0  38.00  
23        3950.0    male  2007     4.0       3950.0  39.50  
24        3800.0    male  2007     3.8       3800.0  38.00  
25        3800.0  female  2007     3.8       3800.0  38.00  
26        3550.0    m

In [50]:
birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Biscoe')].count()

rowid                44
species              44
island               44
bill_length_mm       44
bill_depth_mm        44
flipper_length_mm    44
body_mass_g          44
sex                  44
year                 44
weight               44
body-mass_g          44
wkilo                44
dtype: int64

In [51]:
birds['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

<h2> Adelie on Biscoe Dream

In [52]:
adelie_dream = birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Dream')]

In [53]:
birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Dream')].count()

rowid                56
species              56
island               56
bill_length_mm       56
bill_depth_mm        56
flipper_length_mm    56
body_mass_g          56
sex                  56
year                 56
weight               56
body-mass_g          56
wkilo                56
dtype: int64

In [54]:
adelie_torgersen = birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Torgersen')]

In [55]:
birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Torgersen')].count()

rowid                52
species              52
island               52
bill_length_mm       52
bill_depth_mm        52
flipper_length_mm    52
body_mass_g          52
sex                  52
year                 52
weight               52
body-mass_g          52
wkilo                52
dtype: int64

In [56]:
birds['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

<h1> Insight No. 2 Gentoo only live in Gentoo Island

In [57]:
gentoo_biscoe = birds[(birds['species'] == 'Gentoo') & (birds['island'] == 'Biscoe')].count()

In [58]:
birds[(birds['species'] == 'Gentoo') & (birds['island'] == 'Biscoe')].count()

rowid                124
species              124
island               124
bill_length_mm       124
bill_depth_mm        124
flipper_length_mm    124
body_mass_g          124
sex                  124
year                 124
weight               124
body-mass_g          124
wkilo                124
dtype: int64

In [59]:
gentoo_dream = birds[(birds['species'] == 'Gentoo') & (birds['island'] == 'Dream')].count()

In [60]:
gentoo_torgersen = birds[(birds['species'] == 'Gentoo') & (birds['island'] == 'Torgersen')].count()

In [61]:
birds[(birds['species'] == 'Gentoo') & (birds['island'] == 'Dream')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
body-mass_g          0
wkilo                0
dtype: int64

In [62]:
chinstrap_biscoe = birds[(birds['species'] == 'Chinstrap') & (birds['island'] == 'Biscoe')].count()

In [63]:
birds[(birds['species'] == 'Chinstrap') & (birds['island'] == 'Biscoe')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
body-mass_g          0
wkilo                0
dtype: int64

In [64]:
chinstrap_dream = birds[(birds['species'] == 'Chinstrap') & (birds['island'] == 'Dream')].count()

In [65]:
birds[(birds['species'] == 'Chinstrap') & (birds['island'] == 'Dream')].count()

rowid                68
species              68
island               68
bill_length_mm       68
bill_depth_mm        68
flipper_length_mm    68
body_mass_g          68
sex                  68
year                 68
weight               68
body-mass_g          68
wkilo                68
dtype: int64

In [66]:
chinstrap_torgersen = birds[(birds['species'] == 'Chinstrap') & (birds['island'] == 'Torgersen')].count()

In [67]:
birds[(birds['species'] == 'Chinstrap') & (birds['island'] == 'Torgersen')].count()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
body-mass_g          0
wkilo                0
dtype: int64

<h1> Insight No. 3 Majority of penguins live in Biscoe Island

In [68]:
birds['wkilo'] = np.round(birds['body_mass_g']/ 100,2)

In [69]:
adelie_biscoe = birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Biscoe')] 

In [70]:
adelie_biscoe_w = np.round(adelie_biscoe['wkilo'].mean(),1)
adelie_biscoe_w

np.float64(37.1)

In [71]:
adelie_dream = birds[(birds['species'] == 'Adelie') & (birds['island'] == 'Dream')]

In [72]:
adelie_dream_w = np.round(adelie_dream['wkilo'].mean(),1)
adelie_dream_w

np.float64(36.9)

In [73]:
adelie_torg_w = np.round(adelie_torgersen['wkilo'].mean(),1)
adelie_torg_w

np.float64(37.2)

In [74]:
gentoo_bis_w = np.round(gentoo_biscoe['wkilo'].mean(), 1)
gentoo_bis_w

np.float64(124.0)

In [75]:
gentoo_dream_w = np.round(gentoo_dream['wkilo'].mean(),1)
gentoo_dream_w


np.float64(0.0)

In [76]:
gentoo_torg_w = np.round(gentoo_torgersen['wkilo'].mean(),1)
gentoo_torg_w

np.float64(0.0)

In [77]:
chin_bis_w =  np.round(chinstrap_biscoe['wkilo'].mean(),1)
chin_bis_w

np.float64(0.0)

In [78]:
chin_dream_w = np.round(chinstrap_dream['wkilo'].mean(),1)
chin_dream_w


np.float64(68.0)

In [79]:
chin_torg_w = np.round(chinstrap_torgersen['wkilo'].mean(),1)
chin_torg_w

np.float64(0.0)

<h1> Insight No. 4 The Average Kilo Adelie regardless of island is 3.7 

<h1> Insight No. 5 The Average Kilo of Gentoo on Biscoe Island is 124.0

<h1> Insight No. 6 The Average Kilo of Chinstrap on Torgersen and Dream Islan is 68.0

<h1>insignht n0.7</h1>

<h1>How to use group by</h1>

In [80]:
birds_agg = birds.groupby(['species']).count()

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_16196\2588003792.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  birds_agg = birds.groupby(['species']).count()


In [81]:
birds_agg

rowid  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
species                                                                      
Adelie       152     152             152            152                152   
Chinstrap     68      68              68             68                 68   
Gentoo       124     124             124            124                124   

           body_mass_g  sex  year  weight  body-mass_g  wkilo  
species                                                        
Adelie             152  152   152     152          152    152  
Chinstrap           68   68    68      68           68     68  
Gentoo             124  124   124     124          124    124

In [82]:
birds_agg2 = np.round(birds.groupby(['species','island'])['wkilo'].mean(),1)

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_16196\2357907477.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  birds_agg2 = np.round(birds.groupby(['species','island'])['wkilo'].mean(),1)


In [83]:
birds_agg2

species    island   
Adelie     Biscoe       37.1
           Dream        36.9
           Torgersen    37.2
Chinstrap  Biscoe        NaN
           Dream        37.3
           Torgersen     NaN
Gentoo     Biscoe       50.7
           Dream         NaN
           Torgersen     NaN
Name: wkilo, dtype: float64

In [84]:
birds_agg3 = birds.groupby(['species','island','year','sex']).size()

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_16196\3026250021.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  birds_agg3 = birds.groupby(['species','island','year','sex']).size()


<h1> Insight No. 8  2007 has the most recorded data of male adelie.

In [85]:
birds_agg3.unstack()

sex                       female  male
species   island    year              
Adelie    Biscoe    2007       5     5
                    2008       9     9
                    2009       8     8
          Dream     2007       9    11
                    2008       8     8
                    2009      10    10
          Torgersen 2007       8    12
                    2008       8     8
                    2009       8     8
Chinstrap Biscoe    2007       0     0
                    2008       0     0
                    2009       0     0
          Dream     2007      13    13
                    2008       9     9
                    2009      12    12
          Torgersen 2007       0     0
                    2008       0     0
                    2009       0     0
Gentoo    Biscoe    2007      16    18
                    2008      22    24
                    2009      20    24
          Dream     2007       0     0
                    2008       0     0
                    2009       0     0
          Torgersen 2007       0     0
                    2008       0     0
                    2009       0     0

<h1> Insight No.9 The male penguins are heavier than females. 

In [86]:
weight_year_sx = np.round(birds.groupby(['species', 'sex', 'year' ])['wkilo'].mean() , 1)
weight_year_sx

C:\Users\LAB4-StudentPC37\AppData\Local\Temp\ipykernel_16196\312506435.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  weight_year_sx = np.round(birds.groupby(['species', 'sex', 'year' ])['wkilo'].mean() , 1)


species    sex     year
Adelie     female  2007    33.9
                   2008    33.9
                   2009    33.3
           male    2007    39.6
                   2008    41.0
                   2009    40.0
Chinstrap  female  2007    35.7
                   2008    34.7
                   2009    35.2
           male    2007    38.2
                   2008    41.3
                   2009    39.3
Gentoo     female  2007    46.2
                   2008    46.3
                   2009    47.9
           male    2007    54.7
                   2008    53.8
                   2009    54.0
Name: wkilo, dtype: float64

<h1> Insight No. 10 2009 has the highest recorded weight for female while 2007 has the highest weight recorded for male.

In [87]:
weight_year_sx.unstack()

year              2007  2008  2009
species   sex                     
Adelie    female  33.9  33.9  33.3
          male    39.6  41.0  40.0
Chinstrap female  35.7  34.7  35.2
          male    38.2  41.3  39.3
Gentoo    female  46.2  46.3  47.9
          male    54.7  53.8  54.0

<h1>what is the result of a correlation</h1>
<h1>what is the p value</h1>
<h2> requirement for correlation</h2>
<ul>
    <li>
        Name the correlation
    </li>
    <li>call the column</li>
    <li>test correlation using the .corr() function</li>
    <li>call the second column</li>
</ul>

In [88]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype   
---  ------             --------------  -----   
 0   rowid              344 non-null    category
 1   species            344 non-null    category
 2   island             344 non-null    category
 3   bill_length_mm     344 non-null    float64 
 4   bill_depth_mm      344 non-null    float64 
 5   flipper_length_mm  344 non-null    float64 
 6   body_mass_g        344 non-null    float64 
 7   sex                344 non-null    category
 8   year               344 non-null    category
 9   weight             344 non-null    float64 
 10  body-mass_g        344 non-null    float64 
 11  wkilo              344 non-null    float64 
dtypes: category(5), float64(7)
memory usage: 32.3 KB


<h1>Insignht no11</h1>

In [89]:
b_dep_lenght_cor = birds['bill_length_mm'].corr(birds['bill_depth_mm'])

In [90]:
b_dep_lenght_cor

np.float64(-0.23505287035553282)

<h1>Insignht no12 - 15 </h1>

<h2>Bill lenght has no Correlation with bill Depth</h2>

In [91]:
body_dep_cor = birds['body-mass_g'].corr(birds['bill_depth_mm'])

In [92]:
body_dep_cor

np.float64(-0.47191562118606645)

In [93]:
body_flip_cor = birds['body-mass_g'].corr(birds['flipper_length_mm'])

In [94]:
body_flip_cor

np.float64(0.8712017673060114)

In [95]:
bill_flip_cor = birds['bill_depth_mm'].corr(birds['flipper_length_mm'])

In [96]:
bill_flip_cor

np.float64(-0.5838512164654122)

In [97]:
bill_bill_cor = birds['bill_depth_mm'].corr(birds['bill_length_mm'])

In [98]:
bill_bill_cor

np.float64(-0.23505287035553285)

In [101]:
bill_bill_cor = birds['bill_depth_mm'].corr(birds['bill_length_mm'])

<h1>Correlation between Qualitative and Quantitative</h1>
<h3>Sex and Body Mass</h3>
<h3>Library for one way ANOVA</h3>

In [100]:
pip install scipy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC37\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [103]:
from scipy.stats import f_oneway

<h2>requirements for one way ANNOVA</h2>
<h3>Filter columns and its data</h3>

In [104]:
birds[birds['sex'] == 'male']['body_mass_g']

0      3750.000000
3      4201.754386
5      3650.000000
7      4675.000000
8      3475.000000
          ...     
334    3800.000000
336    3950.000000
339    4000.000000
341    3775.000000
342    4100.000000
Name: body_mass_g, Length: 179, dtype: float64

In [105]:
birds[birds['sex'] == 'female']['body_mass_g']

1      3800.0
2      3250.0
4      3450.0
6      3625.0
12     3200.0
        ...  
335    3525.0
337    3650.0
338    3650.0
340    3400.0
343    3775.0
Name: body_mass_g, Length: 165, dtype: float64

In [108]:
f_stats, p_value = f_oneway(birds[birds['sex'] == 'female']['body_mass_g'],
                            birds[birds['sex'] == 'male']['body_mass_g'])
print(p_value)

3.0226600487050246e-15


<h1>Insight 16.</h1>
<h2>There is a correlation between sex and body mass</h2>